"""Add User model

Revision ID: 9f79accdb0f8
Revises:
Create Date: 2026-07-21 21:19:37.273730

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9f79accdb0f8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
